Vagrant.configure("2") do |config|
  config.vm.define "prod" do |prod|
    prod.vm.box = "generic/oracle9"
    prod.vm.provider "virtualbox" do |v|
      v.name = "prod"  
      v.cpus = 4        
      v.memory = 16384  
    end
    prod.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 7265"
  end
end