version: '3.8'

services:
  app:
    image: preachergoldhand/quotes_app:1.0
    container_name: quotes_app
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - quotes_network

  db:
    image: postgres:17-alpine
    container_name: quotes_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - quotes_data:/var/lib/postgresql/data
      - ./configs/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql 
    networks:
      - quotes_network

  nginx:
    image: nginx:1.27.3-alpine
    container_name: quotes_nginx
    ports:
      - "5500:80"  
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf   
      - ./public:/usr/share/nginx/html  
    depends_on:
      - app
    networks:
      - quotes_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - quotes_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - quotes_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - quotes_network

networks:
  quotes_network:
    driver: bridge

volumes:
  quotes_data:
    driver: local
  grafana_data:
    driver: local
