Vagrant.configure("2") do |config|
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "generic/oracle9"
    jenkins.vm.provider "virtualbox" do |v|
      v.name = "jenkins"  
      v.cpus = 2        
      v.memory = 8192  
    end
    jenkins.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 7265"
  end
end